name: Docker Image CI
on: 
  workflow_dispatch:
    inputs:
      beta:
       type: boolean
       default: 'false'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
       submodules: true
    - name: Build the Docker image
      run: docker build . --file docker/Dockerfile --tag omega:$(date +%s)
